PREFIX wb: <http://hercules-demo.wiki.opencura.com/entity/>
PREFIX wbt: <http://hercules-demo.wiki.opencura.com/prop/direct/>

SELECT ?centreLabel ?researchLineLabel WHERE {
  ?centre wbt:P1 wb:Q2 ; # get entities of type ResearchInstitute
          wbt:P21 ?researchLine . # with property hasResearchLine
  ?researchLine rdfs:label ?researchLineLabel .
  FILTER(?researchLineLabel = "Food Science and Technology"@en)       # research line name to be parametrized
  SERVICE wikibase:label {
    bd:serviceParam wikibase:language "[AUTO_LANGUAGE],es" .
  }
}
ORDER BY DESC(?centreLabel)
