PREFIX wb: <http://hercules-demo.wiki.opencura.com/entity/>
PREFIX wbt: <http://hercules-demo.wiki.opencura.com/prop/direct/>

SELECT ?researchLineLabel (COUNT(?project) AS ?totalProjects) WHERE {
  ?org wbt:P21 ?researchLine ;                    # get entities with property hasResearchLine
       wbt:P1 ?orgType ;
       rdfs:label ?orgLabel .
  ?researchLine wbt:P22 ?researchLineCode .       # get code of researchLine
  ?researchLineCode rdfs:label ?researchLineCodeLabel .
  FILTER(?orgType IN (wb:Q68, wb:Q2))           # organization is either research group or research institute
  ?org wbt:P27 ?project . # get all projects
  SERVICE wikibase:label {
    bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en,es" .
  }
}
GROUP BY (?researchLineLabel)
ORDER BY DESC(COUNT(?project))
LIMIT 10
