PREFIX wb: <http://hercules-demo.wiki.opencura.com/entity/>
PREFIX wbt: <http://hercules-demo.wiki.opencura.com/prop/direct/>

SELECT ?projectLabel ?propLabel ?oLabel WHERE {
  ?project wbt:P1 ?projectType .         # get all projects
  FILTER(?projectType IN (wb:Q94, wb:Q155, wb:Q156, wb:Q157)) # regional, national, european and standard projects

  ?project ?p ?o . # extract all predicates about the project
  ?prop wikibase:directClaim ?p .
  SERVICE wikibase:label {
    bd:serviceParam wikibase:language "en,es" .
  }
}
ORDER BY ?projectLabel
