PREFIX wb: <http://hercules-demo.wiki.opencura.com/entity/>
PREFIX wbt: <http://hercules-demo.wiki.opencura.com/prop/direct/>

SELECT ?associatedUniversityLabel ?centreLabel ?sealLabel WHERE {
  ?centre wbt:P1 wb:Q2 ; # get entities of type ResearchInstitute
          wbt:P2 ?seal ; # with property hasSealOfQuality
          wbt:P34 ?associatedUniversity .
  ?associatedUniversity wbt:P24 wb:Q255 .
  SERVICE wikibase:label {
    bd:serviceParam wikibase:language "en,es" .
  }
}
