PREFIX wb: <http://hercules-demo.wiki.opencura.com/entity/>
PREFIX wbt: <http://hercules-demo.wiki.opencura.com/prop/direct/>

SELECT ?inventorLabel ?patentLabel ?patentDescription WHERE {
  ?patent wbt:P1 wb:Q12 ; # get entities of type Patent
          wbt:P52 ?inventor . # with an inventor
  SERVICE wikibase:label {
    bd:serviceParam wikibase:language "en,es" .
  }
}
ORDER BY DESC(?patentLabel)
