PREFIX wb: <http://hercules-demo.wiki.opencura.com/entity/>
PREFIX wbt: <http://hercules-demo.wiki.opencura.com/prop/direct/>

SELECT DISTINCT ?researcherLabel ?eventLabel WHERE {
  ?researcher wbt:P17 wb:Q44 . # get entities of role Researching
  ?researcher rdfs:label ?researcherLabel .
  FILTER(?researcherLabel = "José Emilio Labra Gayo"@es) # researcher to be parametrized
  ?researcher wbt:P27 ?event . # extract all predicates about the researcher
  ?event wbt:P1 ?eventType .
  FILTER(?eventType IN (wb:Q286, wb:Q287)) # workshops or conferences
  SERVICE wikibase:label {
    bd:serviceParam wikibase:language "en,es" .
  }
}
