PREFIX wb: <http://hercules-demo.wiki.opencura.com/entity/>
PREFIX wbt: <http://hercules-demo.wiki.opencura.com/prop/direct/>

SELECT DISTINCT ?researcherLabel ?coadvisedThesisLabel ?publicationDate WHERE {
  ?researcher wbt:P17 wb:Q44 . # get entities of role Researching
  ?researcher rdfs:label ?researcherLabel .
  FILTER(?researcherLabel = "José Emilio Labra Gayo"@es) # researcher to be parametrized
  ?researcher wbt:P37 ?coadvisedThesis .
  ?coadvisedThesis wbt:P14 ?publicationDate .
  SERVICE wikibase:label {
    bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en,es" .
  }
}
ORDER BY ?publicationDate
