PREFIX wb: <http://hercules-demo.wiki.opencura.com/entity/>
PREFIX wbt: <http://hercules-demo.wiki.opencura.com/prop/direct/>

SELECT ?projectLabel ?projectOutcomeLabel ?projectOutcomeDescription WHERE {
  ?project wbt:P1 ?projectType ;         # get all projects
           wbt:P33 ?projectOutcome  ;    # with an outcome
           wbt:P32 ?researchField .      # and research field
  FILTER(?projectType IN (wb:Q94, wb:Q155, wb:Q156, wb:Q157) && # regional, national, european and standard projects
         ?researchField = wb:Q232) # research field to be parametrized (in this case Food science and technology)
  SERVICE wikibase:label {
    bd:serviceParam wikibase:language "en,es" .
  }
}
ORDER BY ?projectLabel ?projectOutcomeLabel
